// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type UserMetric struct {
	UserID              string    `json:"user_id"`
	PageViewCount       int32     `json:"page_view_count"`
	LastActiveTimestamp time.Time `json:"last_active_timestamp"`
}
