// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserMetric struct {
	UserID        string           `json:"user_id"`
	PageViewCount int32            `json:"page_view_count"`
	LastActiveAt  pgtype.Timestamp `json:"last_active_at"`
}
