// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const upsertUserActivity = `-- name: UpsertUserActivity :exec
INSERT INTO user_metrics (user_id, page_view_count, last_active_timestamp)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET 
    page_view_count = user_metrics.page_view_count + EXCLUDED.page_view_count,
    last_active_timestamp = EXCLUDED.last_active_timestamp
`

type UpsertUserActivityParams struct {
	UserID              string    `json:"user_id"`
	PageViewCount       int32     `json:"page_view_count"`
	LastActiveTimestamp time.Time `json:"last_active_timestamp"`
}

func (q *Queries) UpsertUserActivity(ctx context.Context, arg UpsertUserActivityParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserActivity, arg.UserID, arg.PageViewCount, arg.LastActiveTimestamp)
	return err
}
